apiVersion: v1
kind: Secret
metadata:
    name: aiostreams-secret
    namespace: media
type: Opaque
stringData:
    SECRET_KEY: ENC[AES256_GCM,data:sdFrfgAZXr5OehGPzsER5JbXx7DyZ9lfskxU2Um0UZ9MkWfox79bZ2FVqqr3aUstfptR4L38pJVpqVIUHKS1Rw==,iv:pD9Bq0P4OAa3pRnmC4AHnCXErKq+PoBI/tu8DaJrOlU=,tag:3Sgu0i7GEhwICS5y+Apt+Q==,type:str]
    FORCED_REALDEBRID_API_KEY: ENC[AES256_GCM,data:6MhaImh316hYau7CCtezlylhtzj9fWq5TIqICY7T2ikdNMsDwoQGHE7hlKJH4aRLvkYdQw==,iv:K7uDNlgpScUddqxHNmn9esFQ1EenJ6nBiPSX+hqbvfY=,tag:9hFWkVO+JLP6NRyQH0mHQQ==,type:str]
    FORCED_PREMIUMIZE_API_KEY: ENC[AES256_GCM,data:z1GVuqKMN6osvXDxtWeNXw==,iv:C85OPnBimAG50YMJba1eFISJjOPG9i1LBNaqIqxOovM=,tag:5AoEPHjTxUp4REFms/F+6A==,type:str]
sops:
    age:
        - recipient: age1hvmdhkt8llkq3m00ullewwgycy2ujr8tlhqk6ley07usyexcq9vsz8mymh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQRFJOMFpGSGZDYW10YUVj
            TEF4aUVQSHhQV0pVVWY5QnIyVXh0UDJIY3lBCnlZRTZ0a0dRSGtxVTJJQVUxbzVD
            aWFzcGpQbGVJYjY4QVVTTHlnbjQxUGcKLS0tIE1xT1NrejQvbnYwS2FvZ1pEazJr
            N2tOc1FGZWY3clVIVWxqN3dBc2t6NTgKwGe6Y66AnQLQP114NuGEAoLTp0YfSfMs
            kYmYjOu5DU/v8vj1z0yyizU3l2/ldWjB2SaJFOpD7vHtI4UjpZBipA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-12T10:24:29Z"
    mac: ENC[AES256_GCM,data:xHP8dqhch2s0exgcoIiIhoGzkjbR1i1QP9ajrc5v7pH4z/t1QQCGizpyBIfSRVaHu2eUIoIKkTWoubSEa65UxH5pcWlXfiOc+lsuGXI2tAJSAEFf6KdlMkcDLDMR2leFYQn+T0BbB9KXXYSr8aprzvedvugHdp2/2Zhks/J6nQk=,iv:cfPuYfdrU1ktSL/JqnO5j8B2dmIctvxfZaRaYOkTwf8=,tag:+SdgXfFTTDskJRrkrVBAMw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
