apiVersion: v1
kind: Secret
metadata:
    name: aiostreams-secret
    namespace: media
type: Opaque
stringData:
    SECRET_KEY: ENC[AES256_GCM,data:sdFrfgAZXr5OehGPzsER5JbXx7DyZ9lfskxU2Um0UZ9MkWfox79bZ2FVqqr3aUstfptR4L38pJVpqVIUHKS1Rw==,iv:pD9Bq0P4OAa3pRnmC4AHnCXErKq+PoBI/tu8DaJrOlU=,tag:3Sgu0i7GEhwICS5y+Apt+Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQRFJOMFpGSGZDYW10YUVj
            TEF4aUVQSHhQV0pVVWY5QnIyVXh0UDJIY3lBCnlZRTZ0a0dRSGtxVTJJQVUxbzVD
            aWFzcGpQbGVJYjY4QVVTTHlnbjQxUGcKLS0tIE1xT1NrejQvbnYwS2FvZ1pEazJr
            N2tOc1FGZWY3clVIVWxqN3dBc2t6NTgKwGe6Y66AnQLQP114NuGEAoLTp0YfSfMs
            kYmYjOu5DU/v8vj1z0yyizU3l2/ldWjB2SaJFOpD7vHtI4UjpZBipA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hvmdhkt8llkq3m00ullewwgycy2ujr8tlhqk6ley07usyexcq9vsz8mymh
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-31T10:28:55Z"
    mac: ENC[AES256_GCM,data:dHul3mBI8bBY4wPnxG6mZKVZlecVS897D+13Q3LcuBejjZP3NrFfB7HO9Eg0g1k9tF+BLNQxqGUfCkXggqRYCazjwEXrhk/a86Sulo3+yJfLYllPzJhOD2HTNDoYAf6+Wrj8bpEjE4nmrggrvWJK+TvpFKfd53iTG1K6+Jw5us0=,iv:MLRuGroWhAK+Aqq/sFPnsd0WoksWWqXpeyrd0yObVl0=,tag:5R3n5LQnesj0/bgtCTaYug==,type:str]
    version: 3.13.1
