---
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: jaeger
  namespace: monitoring
spec:
  version: "8.17.0"
  nodeSets:
    - name: default
      count: 1
      config:
        node.store.allow_mmap: false
        cluster.routing.allocation.disk.threshold_enabled: false
        xpack.security.authc.anonymous.username: anonymous
        xpack.security.authc.anonymous.roles: superuser
        xpack.security.authc.anonymous.authz_exception: false
      podTemplate:
        spec:
          containers:
            - name: elasticsearch
              env:
                - name: ES_JAVA_OPTS
                  value: "-Xms512m -Xmx512m"
              resources:
                requests:
                  memory: "1Gi"
                  cpu: "500m"
                limits:
                  memory: "1Gi"
                  cpu: "1"
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes:
              - ReadWriteOnce
            storageClassName: nfs-client
            resources:
              requests:
                storage: 8Gi
  http:
    tls:
      selfSignedCertificate:
        disabled: true
