---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: jaegertracing
  namespace: monitoring
spec:
  interval: 1h
  url: https://jaegertracing.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jaeger
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: jaeger
      version: "4.6.x"
      sourceRef:
        kind: HelmRepository
        name: jaegertracing
        namespace: monitoring
      interval: 1h
  values:
    jaeger:
      ingress:
        enabled: true
        ingressClassName: traefik
        pathType: Prefix
        path: /jaeger
        hosts:
          - monitoring.home.gawbul.io
        tls:
          - secretName: monitoring-tls
            hosts:
              - monitoring.home.gawbul.io
    storage:
      type: elasticsearch
      elasticsearch:
        host: jaeger-es-http.monitoring.svc.cluster.local
        port: 9200
        scheme: http
    esIndexCleaner:
      enabled: true
      schedule: "55 23 * * *"
      numberOfDays: 7
    esRollover:
      enabled: false
    esLookback:
      enabled: false
    userconfig:
      extensions:
        healthcheckv2:
          use_v2: true
          http: {}
        jaeger_storage:
          backends:
            primary_store:
              elasticsearch:
                server_urls:
                  - http://jaeger-es-http.monitoring.svc.cluster.local:9200
                index_prefix: jaeger
        jaeger_query:
          base_path: /jaeger
          storage:
            traces: primary_store
      receivers:
        otlp:
          protocols:
            grpc:
              endpoint: 0.0.0.0:4317
            http:
              endpoint: 0.0.0.0:4318
      processors:
        batch: {}
      exporters:
        jaeger_storage_exporter:
          trace_storage: primary_store
      service:
        extensions:
          - healthcheckv2
          - jaeger_storage
          - jaeger_query
        pipelines:
          traces:
            receivers:
              - otlp
            processors:
              - batch
            exporters:
              - jaeger_storage_exporter
        telemetry:
          metrics:
            level: detailed
            readers:
              - pull:
                  exporter:
                    prometheus:
                      host: 0.0.0.0
                      port: 8888
