---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: jaegertracing
  namespace: monitoring
spec:
  interval: 24h
  url: https://jaegertracing.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jaeger
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: jaeger
      version: "3.4.0"
      sourceRef:
        kind: HelmRepository
        name: jaegertracing
        namespace: monitoring
      interval: 12h
  values:
    provisionDataStore:
      cassandra: false
      elasticsearch: true
    storage:
      type: elasticsearch
    elasticsearch:
      data:
        persistence:
          enabled: true
          storageClass: nfs-client
          size: 8Gi
      master:
        persistence:
          enabled: true
          storageClass: nfs-client
          size: 8Gi
      image:
        repository: bitnamilegacy/elasticsearch
      sysctlImage:
        repository: bitnamilegacy/os-shell
      volumePermissions:
        image:
          repository: bitnamilegacy/os-shell
    collector:
      service:
        otlp:
          grpc:
            name: otlp-grpc
            port: 4317
          http:
            name: otlp-http
            port: 4318
    query:
      enabled: true
      basePath: /jaeger
      ingress:
        enabled: true
        ingressClassName: traefik
        hosts:
          - monitoring.kubernetes.local
        tls:
          - secretName: monitoring-tls
            host:
              - monitoring.kubernetes.local
