---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: kubecost
  namespace: monitoring
spec:
  interval: 24h
  url: https://kubecost.github.io/cost-analyzer
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kubecost
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: cost-analyzer
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: kubecost
        namespace: monitoring
      interval: 12h
  values:
    global:
      prometheus:
        enabled: false
        fqdn: http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local
      grafana:
        enabled: false
        fqdn: http://kube-prometheus-stack-grafana.monitoring.svc.cluster.local
    persistentVolume:
      storageClass: nfs-csi
    ingress:
      enabled: true
      className: traefik
      paths:
        - /kubecost
      hosts:
        - monitoring.kubernetes.local
      tls:
        - secretName: monitoring-tls
          hosts:
            - monitoring.kubernetes.local
