---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mimir
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: mimir-distributed
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: monitoring
      interval: 12h
  values:
    alertmanager:
      persistentVolume:
        storageClass: nfs-csi
    ingester:
      persistentVolume:
        storageClass: nfs-csi
    store_gateway:
      persistentVolume:
        storageClass: nfs-csi
    compactor:
      persistentVolume:
        storageClass: nfs-csi
