---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ollama
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 4.6.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s-labs
        namespace: media
  values:
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"
        nodeSelector:
          workload: ai
        containers:
          main:
            image:
              repository: ollama/ollama
              tag: latest
            env:
              OLLAMA_HOST: "0.0.0.0"
              OLLAMA_KEEP_ALIVE: "24h"
            resources:
              requests:
                memory: 8Gi
                cpu: 2000m
              limits:
                memory: 12Gi
        pod:
          securityContext:
            fsGroup: 1000
    service:
      main:
        ports:
          http:
            port: 11434
    persistence:
      models:
        enabled: true
        storageClass: local-path
        accessMode: ReadWriteOnce
        size: 20Gi
        globalMounts:
          - path: /root/.ollama
