---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: open-telemetry
  namespace: monitoring
spec:
  interval: 24h
  url: https://open-telemetry.github.io/opentelemetry-helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: open-telemetry
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: opentelemetry-operator
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: open-telemetry
        namespace: monitoring
      interval: 12h
  values:
    manager:
      collectorImage:
        repository: "ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib"
      autoInstrumentationImage:
        java:
          repository: "ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-java"
        nodejs:
          repository: "ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-nodejs"
        python:
          repository: "ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-python"
        go:
          repository: "ghcr.io/open-telemetry/opentelemetry-go-instrumentation/autoinstrumentation-go"
      serviceMonitor:
        enabled: true
    admissionWebhooks:
      certManager:
        enabled: true
        issuerRef:
          kind: ClusterIssuer
          name: selfsigned-issuer
      autoGenerateCert:
        enabled: true
