---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: mojo2600
  namespace: networking
spec:
  interval: 1h
  url: https://mojo2600.github.io/pihole-kubernetes/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pihole-primary
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      chart: pihole
      version: "2.35.0"
      sourceRef:
        kind: HelmRepository
        name: mojo2600
        namespace: networking
  values:
    extraInitContainers:
      - name: fix-permissions
        image: busybox:latest
        command: ["sh", "-c", "chown -R 1000:1000 /etc/pihole"]
        securityContext:
          runAsUser: 0
          runAsNonRoot: false
          privileged: true
        volumeMounts:
          - name: config
            mountPath: /etc/pihole
    dnsmasq:
      customDnsEntries:
        - address=/plex.home.gawbul.io/192.168.50.205
        - address=/.home.gawbul.io/192.168.50.204
    persistentVolumeClaim:
      enabled: true
      storageClassName: "local-path"
      accessModes:
        - ReadWriteOnce
      size: 2Gi
    serviceDns:
      type: LoadBalancer
      loadBalancerIP: "192.168.50.206"
      annotations:
        metallb.universe.tf/allow-shared-ip: "pihole-primary"
    serviceWeb:
      type: ClusterIP
    ingress:
      enabled: true
      ingressClassName: traefik
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
      hosts:
        - pihole-primary.home.gawbul.io
      tls:
        - secretName: pihole-primary-tls
          hosts:
            - pihole-primary.home.gawbul.io
    admin:
      existingSecret: pihole-admin-secret
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pihole-secondary
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      chart: pihole
      version: "2.35.0"
      sourceRef:
        kind: HelmRepository
        name: mojo2600
        namespace: networking
  values:
    extraInitContainers:
      - name: fix-permissions
        image: busybox:latest
        command: ["sh", "-c", "chown -R 1000:1000 /etc/pihole"]
        securityContext:
          runAsUser: 0
          runAsNonRoot: false
          privileged: true
        volumeMounts:
          - name: config
            mountPath: /etc/pihole
    dnsmasq:
      customDnsEntries:
        - address=/plex.home.gawbul.io/192.168.50.205
        - address=/.home.gawbul.io/192.168.50.204
    persistentVolumeClaim:
      enabled: true
      storageClassName: "local-path"
      accessModes:
        - ReadWriteOnce
      size: 2Gi
    serviceDns:
      type: LoadBalancer
      loadBalancerIP: "192.168.50.207"
      annotations:
        metallb.universe.tf/allow-shared-ip: "pihole-secondary"
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: app.kubernetes.io/instance
                  operator: In
                  values:
                    - pihole-primary
            topologyKey: "kubernetes.io/hostname"
    serviceWeb:
      type: ClusterIP
    ingress:
      enabled: true
      ingressClassName: traefik
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
      hosts:
        - pihole-secondary.home.gawbul.io
      tls:
        - secretName: pihole-secondary-tls
          hosts:
            - pihole-secondary.home.gawbul.io
    admin:
      existingSecret: pihole-admin-secret
