---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: mojo2600
  namespace: networking
spec:
  interval: 1h
  url: https://mojo2600.github.io/pihole-kubernetes/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pihole
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      chart: pihole
      version: "2.35.0"
      sourceRef:
        kind: HelmRepository
        name: mojo2600
        namespace: networking
  values:
    dnsmasq:
      customDnsEntries:
        - address=/.home.gawbul.io/192.168.50.204
    persistentVolumeClaim:
      enabled: true
      accessModes:
        - ReadWriteOnce
      size: 2Gi
    serviceDns:
      type: LoadBalancer
      loadBalancerIP: "192.168.50.206"
      annotations:
        metallb.universe.tf/allow-shared-ip: "pihole-dns"
    serviceWeb:
      type: ClusterIP
    ingress:
      enabled: true
      ingressClassName: traefik
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
      hosts:
        - pihole.home.gawbul.io
      tls:
        - secretName: pihole-tls
          hosts:
            - pihole.home.gawbul.io
    admin:
      existingSecret: pihole-admin-secret
