apiVersion: v1
kind: Secret
metadata:
    name: plex-secret
    namespace: media
type: Opaque
stringData:
    PLEX_CLAIM: ENC[AES256_GCM,data:lBjnQJ4xYASNZcOySWB3VZnShi2CLU4l5po=,iv:oy78Xz/ptpuI2ul4OnTW8BmXHumGY6p6Du2XwmK3fgU=,tag:tE5Wk5e+vUr7mjxv/OCtBw==,type:str]
sops:
    age:
        - recipient: age1hvmdhkt8llkq3m00ullewwgycy2ujr8tlhqk6ley07usyexcq9vsz8mymh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0VU91MFpDVElZWTJ5Zm1I
            bHJhVHdiSWZucVF2L1BjUmxaNy9uNE00bVc4Cm5rc1lDYjZ1ekFHL1FCSGNqTUo0
            aG9lVDBLd1E5VFg5U1pTUXg5Uzd3bzAKLS0tIHZlSmd6WGZKdW9xRE0vT29oVUd2
            dy9PbCtwWElmcm4vMEFJUWZBcmxtNkkK277QQbbC3bhFV0zASA5VLOHJst/XmGrq
            mllRzMkxiZ1XtOzgxtYq8zIgcNjIVkqb/lIuT1W8OFQP9Wy+WrIWqQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-22T12:14:13Z"
    mac: ENC[AES256_GCM,data:PVZ8pBfiJXZjY4Sb0gwFeGP44UByLCC9zHMNeVQZhMDVTaynaTmJpR7FHnATQzjX0YD8aJfU7NMn+tWQI88BH55RWPjMECt9mR9nCB390NUGcscu42c892GENnoQbHx3z0Y6aB+B7AkTdJPG1192oWmRZbA9rZuoj6Wx1nbVWJo=,iv:Lai9da/N3GOGxmKhvDZ0WdA7xsBxnw6eIgi2+nPa7Sg=,tag:Wi1JIZr/Jolh5fUldvEOzg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
