---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: plex
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 3.2.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-labs
        namespace: media
  values:
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: linuxserver/plex
              tag: latest
            env:
              TZ: Europe/London
              VERSION: docker
              ALLOWED_NETWORKS: "192.168.50.0/24,10.0.0.0/8,172.16.0.0/12"
            envFrom:
              - secretRef:
                  name: plex-secret
            resources:
              requests:
                cpu: 100m
                memory: 1000Mi
              limits:
                memory: 4000Mi
        pod:
          securityContext:
            fsGroup: 101
            fsGroupChangePolicy: "OnRootMismatch"
    service:
      main:
        controller: main
        type: LoadBalancer
        ports:
          http:
            port: 32400
    ingress:
      main:
        enabled: true
        className: traefik
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt
          traefik.ingress.kubernetes.io/router.middlewares: default-strip-prefix@kubernetescrd
        hosts:
          - host: plex.home.gawbul.io
            paths:
              - path: /
                service:
                  identifier: main
                  port: http
        tls:
          - hosts:
              - plex.home.gawbul.io
            secretName: plex-tls
    persistence:
      config:
        enabled: true
        storageClass: local-path
        accessMode: ReadWriteOnce
        size: 20Gi
        globalMounts:
          - path: /config
      movies:
        enabled: true
        existingClaim: media-movies-pvc
        globalMounts:
          - path: /movies
            readOnly: true
      tv:
        enabled: true
        existingClaim: media-tv-pvc
        globalMounts:
          - path: /tv
            readOnly: true
      transcode:
        enabled: true
        type: emptyDir
        medium: Memory
        sizeLimit: 4Gi
        globalMounts:
          - path: /transcode
