---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prowlarr
  namespace: media
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 4.6.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s-labs
        namespace: media
  values:
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: linuxserver/prowlarr
              tag: latest
            env:
              TZ: Europe/London
              PUID: 1024
              PGID: 101
        pod:
          securityContext:
            runAsUser: 1024
            runAsGroup: 101
            fsGroup: 101
            fsGroupChangePolicy: "OnRootMismatch"
    service:
      main:
        ports:
          http:
            port: 9696
    ingress:
      main:
        enabled: true
        className: traefik
        hosts:
          - host: media.kubernetes.local
            paths:
              - path: /prowlarr
                service:
                  identifier: main
                  port: http
    persistence:
      config:
        enabled: true
        storageClass: local-path
        accessMode: ReadWriteOnce
        size: 2Gi
        globalMounts:
          - path: /config
