---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: recommendarr
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 4.6.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s-labs
        namespace: media
  values:
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: tannermiddleton/recommendarr
              tag: latest
            env:
              TZ: Europe/London
              PORT: 3000
              NODE_ENV: production
              PUBLIC_URL: https://recommendarr.home.gawbul.io
              OPENAI_BASE_URL: "http://ollama.media.svc.cluster.local:11434/v1"
              OPENAI_MODEL: "llama3.1"
              OPENAI_API_KEY: "ollama"
            envFrom:
              - secretRef:
                  name: recommendarr-secret
        pod:
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
            fsGroupChangePolicy: "OnRootMismatch"
    service:
      main:
        ports:
          http:
            port: 3000
    ingress:
      main:
        enabled: true
        className: traefik
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt
        hosts:
          - host: recommendarr.home.gawbul.io
            paths:
              - path: /
                service:
                  identifier: main
                  port: http
        tls:
          - hosts:
              - recommendarr.home.gawbul.io
            secretName: recommendarr-tls
    persistence:
      config:
        enabled: true
        storageClass: local-path
        accessMode: ReadWriteOnce
        size: 2Gi
        globalMounts:
          - path: /app/server/data
