---
apiVersion: v1
kind: Namespace
metadata:
  name: reloader
  labels:
    toolkit.fluxcd.io/tenant: gawbul
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: stakater
  namespace: reloader
spec:
  interval: 24h
  url: https://stakater.github.io/stakater-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: reloader
  namespace: reloader
spec:
  interval: 30m
  chart:
    spec:
      chart: reloader
      version: "2.x"
      sourceRef:
        kind: HelmRepository
        name: stakater
        namespace: reloader
      interval: 12h
