---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: stakater
  namespace: default
spec:
  interval: 24h
  url: https://stakater.github.io/stakater-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: reloader
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: reloader
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: stakater
        namespace: default
      interval: 12h
