---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sabnzbd
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 4.6.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s-labs
        namespace: media
  values:
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: linuxserver/sabnzbd
              tag: latest
            env:
              TZ: Europe/London
              PUID: 1024
              PGID: 101
              HOST_WHITELIST_ENTRIES: "home.gawbul.io, sabnzbd, sabnzbd.media, sabnzbd.media.svc.cluster.local"
        pod:
          securityContext:
            runAsUser: 1024
            runAsGroup: 101
            fsGroup: 101
            fsGroupChangePolicy: "OnRootMismatch"
    service:
      main:
        ports:
          http:
            port: 8080
    ingress:
      main:
        enabled: true
        className: traefik
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt
        hosts:
          - host: sabnzbd.home.gawbul.io
            paths:
              - path: /
                service:
                  identifier: main
                  port: http
        tls:
          - hosts:
              - sabnzbd.home.gawbul.io
            secretName: sabnzbd-tls
    persistence:
      config:
        enabled: true
        storageClass: local-path
        accessMode: ReadWriteOnce
        size: 2Gi
        globalMounts:
          - path: /config
      downloads:
        enabled: true
        existingClaim: media-downloads-pvc
        globalMounts:
          - path: /downloads
