---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cilium
  namespace: flux-system
spec:
  interval: 24h
  url: https://helm.cilium.io/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  interval: 30m
  chart:
    spec:
      chart: cilium
      version: "1.x"
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: flux-system
  values:
    k8sServiceHost: 192.168.50.4
    k8sServicePort: 6443
    kubeProxyReplacement: true
    operator:
      replicas: 1
    serviceAccounts:
      cilium:
        name: cilium
      operator:
        name: cilium-operator
    prometheus:
      enabled: true
    hubble:
      enabled: true
      ui:
        enabled: true
      relay:
        enabled: true
    ipam:
      mode: "kubernetes"
    socketLB:
      enabled: false
