---
apiVersion: v1
kind: Namespace
metadata:
  name: nfs-provisioner
  labels:
    toolkit.fluxcd.io/tenant: gawbul
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: nfs-subdir-external-provisioner
  namespace: nfs-provisioner
spec:
  interval: 1h0m0s
  url: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nfs-subdir-external-provisioner
  namespace: nfs-provisioner
spec:
  interval: 30m
  chart:
    spec:
      chart: nfs-subdir-external-provisioner
      version: "4.x"
      sourceRef:
        kind: HelmRepository
        name: nfs-subdir-external-provisioner
        namespace: nfs-provisioner
  values:
    nfs:
      server: 192.168.50.2
      path: /volume1/kubernetes
    storageClass:
      defaultClass: true
      name: nfs-client
