---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 24h
  url: https://traefik.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 30m
  chart:
    spec:
      chart: traefik
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: traefik
      interval: 12h
  values:
    ingressRoute:
      dashboard:
        enabled: true
        matchRule: Host(`traefik.kubernetes.local`)
        entryPoints:
          - websecure
        middlewares:
          - name: traefik-dashboard-auth
        tls:
          secretName: traefik-tls
    metrics:
      addInternals: true
      otlp:
        enabled: true
        grpc:
          enabled: true
    tracing:
      addInternals: true
      otlp:
        enabled: true
        grpc:
          enabled: true
    extraObjects:
      - apiVersion: traefik.io/v1alpha1
        kind: Middleware
        metadata:
          name: traefik-dashboard-auth
        spec:
          basicAuth:
            secret: traefik-dashboard-auth-secret
