---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: plex-tls
  namespace: default
spec:
  secretName: plex-tls
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  duration: 2160h
  renewBefore: 360h
  isCA: false
  usages:
    - server auth
    - client auth
  subject:
    organizations:
      - cert-manager
  commonName: plex.kubernetes.local
  dnsNames:
    - plex.kubernetes.local
    - "*.default.svc.cluster.local"
  emailAddresses:
    - gawbul@gmail.com
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
    group: cert-manager.io
